services:
  server:
    image: unmute-server:latest
    build:
      context: ./
      target: prod
    environment:
      - KYUTAI_STT_URL=ws://tasks.stt:8080
      - KYUTAI_TTS_URL=ws://tasks.tts:8080
    ports:
      - "80:80"
    deploy:
      replicas: 1

  tts:
    image: moshi-server:latest
    command: ["worker", "--config", "configs/tts-prod.toml"]
    build:
      context: services/moshi-server
      dockerfile: private.Dockerfile
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
    volumes:
      - cargo-registry:/root/.cargo/registry
      - moshi-server-target:/app/target
      - uv-cache:/root/.cache/uv
      - hf-cache:/root/.cache/huggingface/hub
      - tts-logs:/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "8"
          memory: 16G

  stt:
    image: moshi-server:latest
    command: ["worker", "--config", "configs/stt-prod.toml"]
    build:
      context: services/moshi-server
      dockerfile: private.Dockerfile
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
    volumes:
      - cargo-registry:/root/.cargo/registry
      - moshi-server-target:/app/target
      - uv-cache:/root/.cache/uv
      - hf-cache:/root/.cache/huggingface/hub
      - stt-logs:/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "8"
          memory: 16G

networks:
  default:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

volumes:
  cargo-registry:
  moshi-server-target:
  uv-cache:
  hf-cache:
  tts-logs:
  stt-logs:
